# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-03 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options_blob', jsonfield.fields.JSONField(default={}, help_text='JSON string containing the extended edunext settings.', verbose_name='Extended Site Options')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'SiteOptions',
            },
        ),
    ]
